export const permissions_to_seed = [
  // {
  //   slug: "list-all-users",
  //   name: "get all users",
  //   route: "/api/v1/users/:id/users",
  //   method: "GET",
  //   description: "List all users",
  // },
  // {
  //   slug: "get-user-detail",
  //   name: "get user detail",
  //   route: "/api/v1/users/:id/users/:id",
  //   method: "GET",
  //   description: "Get User Detail",
  // },
  // {
  //   slug: "create-user",
  //   name: "create user",
  //   route: "/api/v1/users/:id/users",
  //   method: "POST",
  //   description: "Create a new users",
  // },
  // {
  //   slug: "update-user",
  //   name: "update user",
  //   route: "/api/v1/users/:id/users/:id",
  //   method: "PATCH",
  //   description: "update a particular users",
  // },
  // {
  //   slug: "delete-user",
  //   name: "delete user",
  //   route: "/api/v1/users/:id/users/:id",
  //   method: "DELETE",
  //   description: "Delete a particular user",
  // },
  // {
  //   slug: "list-all-group-permissions",
  //   name: "get all permissions by group",
  //   route: "/api/v1/users/:id/groups/permissions",
  //   method: "GET",
  //   description: "List all Permissions",
  // },
  // {
  //   slug: "get-group-detail",
  //   name: "get group detail",
  //   route: "/api/v1/users/:id/groups/:id",
  //   method: "GET",
  //   description: "Get group detail",
  // },
  // {
  //   slug: "create-group",
  //   name: "create group",
  //   route: "/api/v1/users/:id/groups",
  //   method: "POST",
  //   description: "Create a new group",
  // },
  // {
  //   slug: "update-group",
  //   name: "update group",
  //   route: "/api/v1/users/:id/groups/:id",
  //   method: "PATCH",
  //   description: "Update a particular group",
  // },
  // {
  //   slug: "assign-group-permission",
  //   name: "assign permission to group",
  //   route: "/api/v1/users/:id/groups/:id/assign-permissions",
  //   method: "POST",
  //   description: "Assign permissions to group",
  // },
];
